CREATE TABLE IF NOT EXISTS `goldexpert_gold_prices` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `source_price_id` INT NOT NULL,
    `kurs` INT NOT NULL,
    `price_375_from` INT NOT NULL,
    `price_375_to` INT NOT NULL,
    `price_583_from` INT NOT NULL,
    `price_583_to` INT NOT NULL,
    `price_585_from` INT NOT NULL,
    `price_585_to` INT NOT NULL,
    `price_750_from` INT NOT NULL,
    `price_750_to` INT NOT NULL,
    `price_850_from` INT NOT NULL,
    `price_850_to` INT NOT NULL,
    `price_875_from` INT NOT NULL,
    `price_875_to` INT NOT NULL,
    `price_916_from` INT NOT NULL,
    `price_916_to` INT NOT NULL,
    `price_999_from` INT NOT NULL,
    `price_999_to` INT NOT NULL,
    `created_at` DATETIME NOT NULL,
    UNIQUE KEY `uq_source_price_id` (`source_price_id`),
    KEY `idx_created_at` (`created_at`)
) DEFAULT CHARSET=utf8mb4;
