CREATE TABLE IF NOT EXISTS `diamant_gold_prices` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `source_price_id` INT NOT NULL,
    `kurs` INT NOT NULL,
    `375_from` INT NOT NULL,
    `375_to` INT NOT NULL,
    `583_from` INT NOT NULL,
    `583_to` INT NOT NULL,
    `585_from` INT NOT NULL,
    `585_to` INT NOT NULL,
    `750_from` INT NOT NULL,
    `750_to` INT NOT NULL,
    `850_from` INT NOT NULL,
    `850_to` INT NOT NULL,
    `875_from` INT NOT NULL,
    `875_to` INT NOT NULL,
    `916_from` INT NOT NULL,
    `916_to` INT NOT NULL,
    `999_from` INT NOT NULL,
    `999_to` INT NOT NULL,
    `created_at` DATETIME NOT NULL,
    UNIQUE KEY `uq_source_price_id` (`source_price_id`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
